name: Sync remote repositories with target ones
on:
  schedule: # Run schedule every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  sync-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)"
      - uses: actions/checkout@v1
      - name: Sync magento2 repository
        run: bin/mirror-sync.sh magento/magento2 mage-os/magento2
        shell: bash
