name: Sync AdobeDocs/ org upstream repositories into mirrors for mage-os distribution
on:
  schedule: # Run schedule every day at 9:57
    - cron: "57 10 * * *"
  workflow_dispatch:

jobs:
  sync-main-repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - commerce-operations.en
          - commerce-admin.en
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)"
      - uses: actions/checkout@v3
      - name: Sync AdobeDocs/${{ matrix.package }} repository
        run: bin/mirror-sync.sh AdobeDocs/${{ matrix.package }} mage-os/mirror-${{ matrix.package }}
        shell: bash
